title: "Infograf+"

description: "معلومات وإنفوغرافيك بطريقة أبسط"

url: "https://infografplus.com"

baseurl: ""

lang: "ar"

direction: "rtl"

timezone: "Europe/Berlin"

markdown: kramdown

theme: null

permalink: /infographic/:title/

collections:
  posts:
    output: true

include:
  - admin

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "infographic"
      lang: "ar"
      direction: "rtl"
